global using CustomerAccount.DTO;
global using CustomerAccount.Service.Interfaces;
global using Microsoft.AspNetCore.Mvc;
global using CustomerAccount.Data.Classes;
global using CustomerAccount.Data.Interfaces;
global using CustomerAccount.Service.Classes;
global using Microsoft.EntityFrameworkCore;
global using AutoMapper;
global using CustomerAccount.Data.Entities;