global using NServiceBus;
global using Messages.NSB.Events;
global using NServiceBus.Logging;
global using Transaction.Data.Interfaces;
global using Transaction.Service.Interfaces;
global using Transection.DTO;
global using AutoMapper;
global using Transaction.Data.Entities;
global using System.Security.Claims;