// <auto-generated />
#nullable disable

namespace Transaction.Data.Migrations;

[DbContext(typeof(TransactionContext))]
partial class TransactionContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

        modelBuilder.Entity("Transaction.Data.Entities.Transaction", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                b.Property<int>("Ammount")
                    .HasColumnType("int");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<string>("FailureReason")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("FromAccount")
                    .HasColumnType("int");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int>("ToAccount")
                    .HasColumnType("int");

                b.HasKey("ID");

                b.ToTable("Transaction");
            });
#pragma warning restore 612, 618
    }
}
